### ISSUE TITLE
Importing the module

### ISSUE THREAD

**Issue by blakkheimgw** [p4r4n0y1ng/pyfgt#1]
Hello,

I've a probably stupid question, but how can I import the module pyFGT in a custom script ? I can't seem to be able to import it in my scripts. I can do a simple : 
`import pyFGT`

Python doesn't return any error but when I want to use the FortiGate class as described in the documentation, I get : 
`AttributeError: module 'pyFGT' has no attribute 'FortiGate'`

And if I try to list the functions of the module with the dir function, I get : 
```
>>> dir (pyFGT)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```
FYI, I use Python 3.7

Thanks for your help.

**Comment by p4r4n0y1ng** [comment]
The main file in the package is called "fortigate" so you can do several things. The easiest though is just do:

from pyFGT.fortigate import FortiGate

this means you won't get the exceptions though, you'd need to add all of them to that call so something like this:

from pyFGT.fortigate import FortiGate, FGTBaseException, FGTValidSessionException, FGTValueError, FGTResponseNotFormedCorrect,FGTConnectionError, FGTConnectTimeout

would give you everything, but you really only want to do that if you're catching all the exceptions too. You could also just import the whole thing (pyFGT) and then use the long names in your code, but easiest and best (IMHO) is how I show you above.

**Comment by blakkheimgw** [comment]
Hello,

You got it, _from pyFGT.fortigate import FortiGate_ works as expected.

Thank you for your help.

Regards.
